package main

import (
	"bytes"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/BurntSushi/toml"
)

var (
	fileTemplate = template.Must(template.New("locales").Parse(`// Code generated by i18n-codegen. DO NOT EDIT.
package i18n

var EmbeddedLocales = map[string]map[string]string{
{{- range $lang, $messages := . }}
	"{{ $lang }}": {
{{- range $key, $value := $messages }}
		"{{ $key }}": {{ printf "%q" $value }},
{{- end }}
	},
{{- end }}
}
`))
)

func main() {
	var inPath, outPath string
	flag.StringVar(&inPath, "in", "", "Input directory containing TOML files")
	flag.StringVar(&outPath, "out", "", "Output Go file to generate")
	flag.Parse()

	if inPath == "" || outPath == "" {
		log.Fatal("-in and -out flags are required")
	}

	files, err := filepath.Glob(filepath.Join(inPath, "*.toml"))
	if err != nil {
		log.Fatalf("Failed to glob for TOML files: %v", err)
	}

	masterMap := make(map[string]map[string]string)

	for _, file := range files {
		langCode := strings.TrimSuffix(filepath.Base(file), ".toml")

		var domainMessages map[string]map[string]string
		if _, err := toml.DecodeFile(file, &domainMessages); err != nil {
			log.Fatalf("Failed to decode TOML file %s: %v", file, err)
		}

		masterMap[langCode] = flatten(domainMessages)
	}

	var buffer bytes.Buffer
	if err := fileTemplate.Execute(&buffer, masterMap); err != nil {
		log.Fatalf("Failed to execute template: %v", err)
	}

	if err := os.WriteFile(outPath, buffer.Bytes(), 0644); err != nil {
		log.Fatalf("Failed to write output file %s: %v", outPath, err)
	}

	fmt.Printf("Successfully generated %s from %d language(s)\n", outPath, len(masterMap))
}

// flatten takes a map of domains and their messages and flattens it
// into a single-level map with keys like "domain.key".
func flatten(data map[string]map[string]string) map[string]string {
	flat := make(map[string]string)
	for domain, messages := range data {
		for key, value := range messages {
			flat[domain+"."+key] = value
		}
	}
	return flat
}
