# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  testrunner:
    taskfile: Taskfile.testrunner.yml

tasks:
  test:
    desc: Run acceptance tests
    cmds:
      - task: testrunner:test
