package scaffold

import (
	"encoding/json"
	"os"
	"path/filepath"
)

// Manifest tracks files generated by the kata and their expected checksums.
type Manifest struct {
	Files map[string]FileEntry `json:"files"`
}

// FileEntry describes a generated file.
type FileEntry struct {
	Checksum string `json:"checksum"`
	Source   string `json:"source"`
}

// LoadManifest loads the manifest from disk or creates a new one if missing.
func LoadManifest(root string) (*Manifest, error) {
	path := manifestPath(root)

	if _, err := os.Stat(path); os.IsNotExist(err) {
		return &Manifest{Files: map[string]FileEntry{}}, nil
	}

	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	var m Manifest
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}

	return &m, nil
}

// Save persists the manifest to disk.
func (m *Manifest) Save(root string) error {
	path := manifestPath(root)

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}

	data, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		return err
	}

	return os.WriteFile(path, data, 0o644)
}

func manifestPath(root string) string {
	return filepath.Join(root, ".kata", "manifest.json")
}
