name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: false
      - name: Generate files
        run: go generate ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
      - name: Run i18n-lint
        run: go run tools/i18n-lint/main.go

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Generate files
        run: go generate ./...
      - name: Test
        run: go test -v ./...

  vulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - name: Generate files
        run: go generate ./...
      - name: Run govulncheck
        run: govulncheck ./...
